1.⁠ ⁠(1 ponto) Write Python code from scratch to find error metrics of deep learning model. Actual
values and deep learning model predicted values are shown in Table 1. Also compare the results
with the outcomes of libraries
YActual YP red
20 20.5
30 30.3
40 40.2
50 50.6
60 60.7


In [7]:
import numpy as np
y_test=[20,30,40,50,60]
y_pred=[20.5,30.3,40.2,50.6,60.7]
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error: {rmse}")
r2 = r2_score(y_test, y_pred)
print(f"R-squared : {r2}")

Mean Squared Error: 0.24600000000000147
Root Mean Squared Error: 0.49598387070549127
R-squared : 0.99877


In [8]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error: {rmse}")
r2 = r2_score(y_test, y_pred)
print(f"R-squared : {r2}")

Mean Squared Error: 0.24600000000000147
Root Mean Squared Error: 0.49598387070549127
R-squared : 0.99877


2.⁠ ⁠(1 ponto) Write python code from scratch to find evaluation metrics of deep learning model.
Actual values and deep learning model predicted values are shown in Table 2. Also compare the
results with outcome of libraries
YActual YP red
0 0 1 1 2 0
0 0 1 0 2 0
0 1 1 2 2 1
0 2 1 0 2 2
0 2 1 2 2 2
Tabela 2: YActual Vs. YP red

In [9]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_actual = np.array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
y_pred = np.array([0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2])
conf_matrix = confusion_matrix(y_actual, y_pred)


acc = accuracy_score(y_actual, y_pred)
prec = precision_score(y_actual, y_pred, average='macro')
recall = recall_score(y_actual, y_pred, average='macro')
f1 = f1_score(y_actual, y_pred, average='macro')

print("Confusion Matrix:")
print(conf_matrix)
print(f"Accuracy: {acc}")
print(f"Precision: {prec}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Confusion Matrix:
[[2 1 2]
 [3 0 2]
 [2 1 2]]
Accuracy: 0.26666666666666666
Precision: 0.20634920634920637
Recall: 0.26666666666666666
F1 Score: 0.23232323232323235


In [10]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
conf_matrix_lib = confusion_matrix(y_actual, y_pred)
accuracy_lib = accuracy_score(y_actual, y_pred)
precision_lib = precision_score(y_actual, y_pred, average='macro')
recall_lib = recall_score(y_actual, y_pred, average='macro')
f1_lib = f1_score(y_actual, y_pred, average='macro')

print("Confusion Matrix (lib):")
print(conf_matrix_lib)
print(f"Accuracy (lib): {accuracy_lib}")
print(f"Precision (lib): {precision_lib}")
print(f"Recall (lib): {recall_lib}")
print(f"F1 Score (lib): {f1_lib}")

Confusion Matrix (lib):
[[2 1 2]
 [3 0 2]
 [2 1 2]]
Accuracy (lib): 0.26666666666666666
Precision (lib): 0.20634920634920637
Recall (lib): 0.26666666666666666
F1 Score (lib): 0.23232323232323235
